name: Maven Build and Test

# Trigger this workflow on pushes to the main branch or when pull requests are created.
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    # Checkout the repository code.
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up JDK 8 for Maven (matches the `pom.xml`).
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '17.0.12+7'
        distribution: 'temurin'

    # Cache Maven dependencies to speed up builds.
    - name: Cache Maven packages
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

     # Run the test suite (TestNG with Cucumber).
    - name: Run Tests with Maven Surefire Plugin
      run: mvn install

    # Upload Extent Reports if they are generated.
    - name: Upload Test Reports
      if: always() # Runs even if the previous steps fail
      uses: actions/upload-artifact@v3
      with:
        name: extent-reports
        path: test-reports/chrome  # Adjust this path to where your reports are generated

    # Optionally, you can add more steps for specific environments or notifications.
